title: DD
author: Dan Dix
email: dddix2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my page
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
